version: "3"
services:
  wordpress:
    build: ./dockerfiles/wordpress
    volumes:
      - .:/var/www/html
      - tmp:/tmp
    depends_on:
      - "mysql"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

volumes:
  tmp:
    driver: local
